server:
  port: 10101

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

logs-mappings:
  applications:
    - supported-applications-keywords: [ nginx ]
      mapping:
        warning-keywords: [ "warn", "warning" ]
        error-keywords:
          - "[error]"
          - "[ERROR]"
          - "[crit]"
          - "[CRIT]"
          - "[alert]"
          - "[ALERT]"
          - "[emerg]"
          - "[EMERG]"

  default-mapping:
    warning-keywords: [ "WARNING", "warning", "WARN", "warn" ]
    error-keywords: [ "ERROR", "error" ]

logs-storage:
  file-path: "${LOGS_STORAGE_FILE_PATH:/tmp/logs}"
  # 10MB
  max-file-size: 10_000_000
  max-files: 50

logs-cleaner:
  initial-delay: "PT1M"
  fixed-delay: "PT1H"

prometheus-health-check:
  initial-delay: "PT5S"
  fixed-delay: "PT60S"
  url: "http://localhost:9090/-/healthy"

