/*
 * This file is generated by jOOQ.
 */
package io.codyn.commons.sqldb.schema.user;


import io.codyn.commons.sqldb.schema.user.tables.ActivationToken;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in user.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACTIVATION_TOKEN_EXPIRES_AT = Internal.createIndex(DSL.name("activation_token_expires_at"), ActivationToken.ACTIVATION_TOKEN, new OrderField[] { ActivationToken.ACTIVATION_TOKEN.EXPIRES_AT }, false);
}
