/*
 * This file is generated by jOOQ.
 */
package io.codyn.commons.sqldb.schema.user;


import io.codyn.commons.sqldb.schema.user.tables.ActivationToken;
import io.codyn.commons.sqldb.schema.user.tables.User;


/**
 * Convenience access to all tables in user.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user.activation_token</code>.
     */
    public static final ActivationToken ACTIVATION_TOKEN = ActivationToken.ACTIVATION_TOKEN;

    /**
     * The table <code>user.user</code>.
     */
    public static final User USER = User.USER;
}
