/*
 * This file is generated by jOOQ.
 */
package io.codyn.commons.sqldb.schema.user;


import io.codyn.commons.sqldb.schema.user.tables.ActivationToken;
import io.codyn.commons.sqldb.schema.user.tables.Role;
import io.codyn.commons.sqldb.schema.user.tables.SecondFactorAuthentication;
import io.codyn.commons.sqldb.schema.user.tables.User;


/**
 * Convenience access to all tables in user.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user.activation_token</code>.
     */
    public static final ActivationToken ACTIVATION_TOKEN = ActivationToken.ACTIVATION_TOKEN;

    /**
     * The table <code>user.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>user.second_factor_authentication</code>.
     */
    public static final SecondFactorAuthentication SECOND_FACTOR_AUTHENTICATION = SecondFactorAuthentication.SECOND_FACTOR_AUTHENTICATION;

    /**
     * The table <code>user.user</code>.
     */
    public static final User USER = User.USER;
}
