spring:
  profiles:
    active: "${ENV}"
  application:
    name: app-sockets-server-template
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

server:
  port: "${SERVER_PORT:10101}"

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]