server:
  port: 10101

logs-mappings:
  applications:
    - supported-applications-keywords: [ nginx ]
      mapping:
        warning-keywords: [ "warn", "warning" ]
        error-keywords:
          - "[error]"
          - "[ERROR]"
          - "[crit]"
          - "[CRIT]"
          - "[alert]"
          - "[ALERT]"
          - "[emerg]"
          - "[EMERG]"

  default-mapping:
    warning-keywords: [ "WARNING", "warning", "WARN", "warn" ]
    error-keywords: [ "ERROR", "error" ]

logs-storage:
  file-path: "${LOGS_STORAGE_FILE_PATH:/tmp/logs}"
  # 25MB
  max-file-size: 25_000_000

logs-cleaner:
  max-log-files: 20
  initial-delay: "PT1M"
  fixed-delay: "PT1H"


management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]