server:
  port: 10101

log-mappings:
  applications:
    - supportedApplicationsKeywords: [ nginx ]
      mapping:
        warningKeywords: [ "warn", "warning" ]
        errorKeywords:
          - "[error]"
          - "[ERROR]"
          - "[crit]"
          - "[CRIT]"
          - "[alert]"
          - "[ALERT]"
          - "[emerg]"
          - "[EMERG]"

  defaultMapping:
    warningKeywords: [ "WARNING", "WARN" ]
    errorKeywords: [ "ERROR" ]

logs-storage:
  filePath: "${LOGS_STORAGE_FILE_PATH:/tmp/logs}"
  maxFileSize: 5000000

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]