server:
  port: 10101

log-mappings:
  applications: [ ]
  defaultMapping:
    warningKeywords: [ "WARNING", "WARN" ]
    errorKeywords: [ "ERROR" ]

logs-storage:
  filePath: "/tmp/logs"

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]