/*
 * This file is generated by jOOQ.
 */
package io.codyn.commons.sqldb.schema.project;


import io.codyn.commons.sqldb.schema.project.tables.Project;
import io.codyn.commons.sqldb.schema.project.tables.ProjectUser;
import io.codyn.commons.sqldb.schema.project.tables.Task;


/**
 * Convenience access to all tables in project.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>project.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>project.project_user</code>.
     */
    public static final ProjectUser PROJECT_USER = ProjectUser.PROJECT_USER;

    /**
     * The table <code>project.task</code>.
     */
    public static final Task TASK = Task.TASK;
}
