global:
  scrape_interval: 30s
  scrape_timeout: 5s
  evaluation_interval: 30s

rule_files:
  - "alert_rules.yml"
  # - "second.rules"


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: prometheus-alertmanager
    static_configs:
      - targets: ['localhost:9093']
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
  - job_name: fluentd
    static_configs:
      - targets: ['localhost:24231']
  - job_name: system-monitor
    metrics_path: "/actuator/prometheus"
    static_configs:
        - targets: ['localhost:10101']
  - job_name: some-custom-app
    static_configs:
        - targets: ['localhost:8080']