{
 "title": "Alerts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System monitor health check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"system-monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus health check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert manager health check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus-alertmanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker metrics collectors health check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - monitoring_collector_up_timestamp_seconds",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Alerts in the last 15m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(monitoring_alerts_total{status=\"firing\"}[15m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts in the last 6h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(monitoring_alerts_total{status=\"firing\"}[6h])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts in the last 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(monitoring_alerts_total{status=\"firing\"}[24h])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "New alerts in time",
   "type": "timeseries",
   "description": "Count of new alerts, appearing in the 15 minutes time window",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (status) (increase(monitoring_alerts_total[15m]))",
     "legendFormat": "{{label_alertname}}"
    }
   ]
  },
  {
   "title": "New alerts details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(monitoring_alerts_total{status=\"firing\"}[15m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}