{
 "title": "Application",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(monitoring_application_up_timestamp_seconds, application)"
    }
   },
   {
    "name": "instance_id",
    "label": "instance",
    "query": {
     "query": "label_values(monitoring_application_up_timestamp_seconds{application=\"$application\"}, instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last UP",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (application, source, instance_id) (monitoring_application_up_timestamp_seconds{application=\"$application\"} * 1000)",
     "legendFormat": "{{source}}-{{application}}-{{instance_id}}"
    }
   ]
  },
  {
   "title": "Application instance uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitoring_application_started_at_timestamp_seconds{application=\"$application\", instance_id=\"$instance_id\"}"
    }
   ]
  },
  {
   "title": "CPU  usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "monitoring_application_cpu_usage_percent{application=\"$application\", instance_id=\"$instance_id\"}",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "monitoring_application_logs_warnings_total{application=\"$application\", instance_id=\"$instance_id\"} or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "monitoring_application_logs_errors_total{application=\"$application\", instance_id=\"$instance_id\"} or vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "monitoring_application_used_memory_bytes{application=\"$application\", instance_id=\"$instance_id\"} / monitoring_application_max_memory_bytes{application=\"$application\", instance_id=\"$instance_id\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Last stats averages",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(monitoring_application_used_memory_bytes{application=\"$application\", instance_id=\"$instance_id\"}[5m])",
     "legendFormat": "used memory"
    },
    {
     "expr": "avg_over_time(monitoring_application_max_memory_bytes{application=\"$application\", instance_id=\"$instance_id\"}[5m])",
     "legendFormat": "max memory"
    },
    {
     "expr": "avg_over_time(monitoring_application_cpu_usage_percent{application=\"$application\", instance_id=\"$instance_id\"}[5m])",
     "legendFormat": "Used CPU"
    }
   ]
  }
 ]
}