spring:
  application:
    name: system-monitor

server:
  port: "${SERVER_PORT:9999}"

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

logs-mappings:
  applications:
    - supported-applications-keywords: [ nginx ]
      mapping:
        warning-keywords: [ "warn", "warning" ]
        error-keywords:
          - "[error]"
          - "[ERROR]"
          - "[crit]"
          - "[CRIT]"
          - "[alert]"
          - "[ALERT]"
          - "[emerg]"
          - "[EMERG]"
        messages-to-swallow:
          - "SSL_do_handshake() failed"
          - "access forbidden by rule"

  default-mapping:
    warning-keywords: [ "WARNING", "warning", "WARN", "warn" ]
    error-keywords: [ "ERROR", "error" ]

logs-storage:
  file-path: "${LOGS_STORAGE_FILE_PATH:/tmp/logs}"
  # 10MB
  max-file-size: 10_000_000
  max-files: 25

logs-cleaner:
  initial-delay: "PT1M"
  fixed-delay: "PT1H"

prometheus-health-check:
  initial-delay: "PT5S"
  fixed-delay: "PT1M"
  url: "http://localhost:9090/-/healthy"
  retry-times: 10
  retry-interval: 2000

