spring:
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5678/system-template}"
    username: "${DB_USER:system-template}"
    password: "${DB_PASSWORD:system-template}"

#See docs: https://springdoc.org/v2/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  email:
    fake-server: true