spring:
  application:
    name: app-template

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

app:
  jwt:
    issuer: system-template
    token-key: "xCwZ4zydRbu8kbKre59Hi2224Xdz0PupADTWkErvIg4="
    access-token-duration: "PT1H"
    refresh-token-duration: "PT24H"