spring:
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5678/system-template}"
    username: "${DB_USER:system-template}"
    password: "${DB_PASSWORD:system-template}"

#See docs: https://springdoc.org/v2/
springdoc:
  api-docs:
    enabled: true
    path: /swagger/v3/api-docs/swagger-config
  swagger-ui:
    enabled: true
  default-produces-media-type: application/json

app:
  email:
    fake-server: true
  jwt:
    #valid, random token key for using tokens locally
    token-key: "xCwZ4zydRbu8kbKre59Hi2224Xdz0PupADTWkErvIg4"