spring:
  profiles:
    active: "${ENV}"
  application:
    name: app-template
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

server:
  port: "${SERVER_PORT:-8080}"

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

#Real values
app:
  jwt:
    issuer: system-template
    token-key: "${JWT_TOKEN_KEY}"
    access-token-duration: "PT1H"
    refresh-token-duration: "PT24H"
  email:
    fake-server: false
    templates-dir: "${TEMPLATES_DIR:/templates}"
    postmark-api-token: "${POSTMARK_API_TOKEN}"
    # TODO: impl!
    postmark-webhook-token: "${POSTMARK_WEBHOOK_TOKEN}"
    frontend-domain: "https://codyn.io"
    from-email:
      name: Admin
      email: "app@codyn.io"
    user:
      user-activation-url: "sign-in"
      sign-up-url: "sign-up"
      email-change-confirmation-url: "user-account"
      password-reset-url: "forgot-password"
      new-password-url: "new-password"